import './globals.css'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Cours nextJS 13: episode 8',
    description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
    return (
        <>

            <p>
                <a href="/todos_actions">GO TO <b>SERVER</b> COMPONENT FOR NEXTJS ACTION</a>
            </p>
            <p>
                <a href="/todos_actions/client">GO TO <b>CLIENT</b> COMPONENT FOR NEXTJS ACTION (didn't worked yet)</a>
            </p>
            <hr />

            {children}

            <hr />
            <p><b>NB:</b> LORSQUE L'ON UTILISE LES NEXTJS ACTIONS <u>DANS DES CLIENT COMPONENTS</u>, IL EST NÉCESSAIRE DE PASSER LA FONCTION DE L'ACTION <b>VIA LES PROPS DU COMPOSANT PARENT</b>(SERVER COMPONENT) VERS L'ENFANT(CLIENT COMPONENT) POUR NE PAS GÉNÉRER D'ERREUR.</p>
            <hr />

            <ul>
                <li><a href="https://github.com/HamedBahram/next-13-4">tuto's repo</a></li>
                <li><a href="https://www.youtube.com/results?search_query=Mutate+data+using+Server+Actions+in+NextJs+13.4">tuto's video</a></li>
                <li><a href="https://www.youtube.com/watch?v=O94ESaJtHtM&ab_channel=BeyondFireship">fireship video about nextjs actions</a></li>
            </ul>
        </>
    )
}

export default RootLayout
